version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_wp
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD_FILE: /run/secrets/wp_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - wp_db_password
      - mysql_root_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wp_db_password
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - wp_db_password
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:

secrets:
  wp_db_password:
    external: true
  mysql_root_password:
    external: true

